[project]
name = "tydi"
version = "0.3.0"
description = "Multiple dispatch with type support"
readme = "README.md"
package-mode = true
packages = [{include = "tydi", from = "src"}]
requires-python = "<3.12.0a1,>=3.11"
authors = [
    {name = "Rama Krishna", email = ""},
]
include = ["src/tydi/py.typed"]


dependencies = [
    "beartype>=0.21.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
